#!/bin/bash
printf -- "----------------\n"
printf -- "Run NGINX Server\n"
printf -- "----------------\n"
#sudo nginx 
conf="/home/compu/code/valencia_college/step_3/config/nginx.conf"
sudo nginx -c "${conf}"
